// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBngH9tWARK17usTcW0ZTGlvwsbPp1dmPQ',
    appId: '1:218605475716:web:53ee692c12f17a08832fd1',
    messagingSenderId: '218605475716',
    projectId: 'horas-v3-e7265',
    authDomain: 'horas-v3-e7265.firebaseapp.com',
    storageBucket: 'horas-v3-e7265.firebasestorage.app',
    measurementId: 'G-29ZXPMP66Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-4tEv7vfKeKtiFm3WOMPzzkvQWvtTgM',
    appId: '1:218605475716:android:f939998e1c787e06832fd1',
    messagingSenderId: '218605475716',
    projectId: 'horas-v3-e7265',
    storageBucket: 'horas-v3-e7265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCahIVEY8DDDE_XKAVxjt5qBYHst82gNOs',
    appId: '1:218605475716:ios:b09418756d34446d832fd1',
    messagingSenderId: '218605475716',
    projectId: 'horas-v3-e7265',
    storageBucket: 'horas-v3-e7265.firebasestorage.app',
    iosBundleId: 'com.example.horasV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCahIVEY8DDDE_XKAVxjt5qBYHst82gNOs',
    appId: '1:218605475716:ios:b09418756d34446d832fd1',
    messagingSenderId: '218605475716',
    projectId: 'horas-v3-e7265',
    storageBucket: 'horas-v3-e7265.firebasestorage.app',
    iosBundleId: 'com.example.horasV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBngH9tWARK17usTcW0ZTGlvwsbPp1dmPQ',
    appId: '1:218605475716:web:94d6b1eee02bdd5f832fd1',
    messagingSenderId: '218605475716',
    projectId: 'horas-v3-e7265',
    authDomain: 'horas-v3-e7265.firebaseapp.com',
    storageBucket: 'horas-v3-e7265.firebasestorage.app',
    measurementId: 'G-2XDY2N1JWL',
  );

}